FH.Agent-Web/Models/PropertyType.cs
using System.Collections.Generic;

namespace FH.User_Web
{
    public class PropertyType
    {
        public static IDictionary<string, string> GetAll()
        {
            IDictionary<string, string> lstType = new Dictionary<string, string>();
            lstType.Add("Flat", "Flat");
            lstType.Add("Room", "Room");
            lstType.Add("Flatmate", "FlatMate");
            lstType.Add("PG", "PG");
            return lstType;
        }

    }
}

FH.Agent-Web/Controllers/PropertyController.cs
using System.Web.Mvc;
using FH.Web.Security;
using FH.User.Entities;
using System.Collections.Generic;
using FH.User.Service;
using System;
using System.Linq;
using System.Web;
using System.IO;
using System.Globalization;
using FH.Util;
using FH.Agent_Web;

namespace FH.User_Web.Controllers
{
    [CustomAuthorize]
    public class PropertyController : Controller
    {
        [HttpGet]     
        public ActionResult PostYourProperty()
        {
            if (CurrentUser.User != null)
                ViewBag.IsLoggedInUser ="yes";
            else
                ViewBag.IsLoggedInUser ="no";
            return View();
        }

        [HttpGet]
        public ActionResult Post()
        {
           // CityMasterBL _cityBL = new CityMasterBL();

            using (var uow = new UnitOfWork())
            {
                ViewBag.furnishingMaster=uow.FurnishingMaster.GetAll();
                ViewBag.amenityMaster=uow.AmenityMaster.GetAll();
            }
           // ViewBag.cityMaster = _cityBL.GetAllCity();
            return View();
        }

        [HttpGet]
        public ActionResult PostPG()
        {
           // CityMasterBL _cityBL = new CityMasterBL();

            using (var uow = new UnitOfWork())
            {                
                var amenities = uow.AmenityMaster.GetAll("PG");
                ViewBag.roomAmenity = amenities.Where(x => x.AmenityType == "PGRoom");
                ViewBag.pgAmenity = amenities.Where(x => x.AmenityType == "PG");               
            }

             // ViewBag.cityMaster=_cityBL.GetAllCity();

            return View();
        }
        
        [HttpPost]
        [AjaxRequestValidation]
        public ActionResult PostFlatRoom(PropertyFlatRoom property)
        {   
            /*********Property Detail **********/
            if(string.IsNullOrEmpty(property.PropertyMaster.PropertyType))
             return ValidationError("Property type required."); 

            string propertyType = property.PropertyMaster.PropertyType.ToUpper();
            if (propertyType != EnPropertyType.Flat.ToString().ToUpper() && propertyType != EnPropertyType.Room.ToString().ToUpper() && propertyType != EnPropertyType.Flatmate.ToString().ToUpper())
                return ValidationError("Invalid Property type.");
            
            if(string.IsNullOrWhiteSpace(property.PropertyDetail.ApartmentType))
                return ValidationError("Apartment type required.");
            if (!ApartmentType.GetAll().ContainsKey(property.PropertyDetail.ApartmentType))
                return ValidationError("Invalid apartment type.");

            if (propertyType=="FLAT" ||propertyType=="FLATMATE")
            {
                if(string.IsNullOrWhiteSpace(property.PropertyDetail.BhkType))
                    return ValidationError("BHK type required.");
                if(!BHKType.GetAll().ContainsKey(property.PropertyDetail.BhkType))
                    return ValidationError("Invalid BHK type.");

            }   

            if(propertyType == "FLATMATE" || propertyType == "ROOM")
             {
                 if(string.IsNullOrWhiteSpace(property.PropertyDetail.RoomType))
                    return ValidationError("Room type required.");
                 if(!RoomType.GetAll().ContainsKey(property.PropertyDetail.RoomType))
                    return ValidationError("Invalid Room type.");
             }

            if (propertyType == "FLATMATE")
            {                
                if (!string.IsNullOrWhiteSpace(property.PropertyDetail.TenantGender) && property.PropertyDetail.TenantGender.ToLower() != "male" && property.PropertyDetail.TenantGender.ToLower() != "female")
                    return ValidationError("Invalid gender type.");
            }

            else if (!string.IsNullOrWhiteSpace(property.PropertyDetail.PropertySize) && (property.PropertyDetail.PropertySize.Length > 5 || !Validation.IsInt(property.PropertyDetail.PropertySize)))
                return ValidationError("Invalid Property size.");

            if (!string.IsNullOrWhiteSpace(property.PropertyDetail.Facing) && !FacingType.GetAll().ContainsKey(property.PropertyDetail.Facing))
                return ValidationError("Invalid facing type.");
            
            if (!string.IsNullOrWhiteSpace(property.PropertyDetail.PropertyAge) && !PropertyAgeType.GetAll().ContainsKey(property.PropertyDetail.PropertyAge))
                return ValidationError("Invalid property age.");
            
            if(property.PropertyDetail.FloorNo!=null && property.PropertyDetail.TotalFloor==null)
                return ValidationError("Total floor required.");
            if (property.PropertyDetail.FloorNo == null && property.PropertyDetail.TotalFloor != null)
                return ValidationError("Floor no required.");
            if (property.PropertyDetail.FloorNo != null && property.PropertyDetail.TotalFloor != null && property.PropertyDetail.FloorNo > property.PropertyDetail.TotalFloor)
                return ValidationError("Floor can't be greater than Total Floor.");
            
            if (!string.IsNullOrWhiteSpace(property.PropertyDetail.WaterSupply) && ! WaterSupplyType.GetAll().ContainsKey(property.PropertyDetail.WaterSupply))
                return ValidationError("Invalid water supply type.");

            if (!string.IsNullOrWhiteSpace(property.PropertyDetail.GateSecurity) && property.PropertyDetail.GateSecurity != "Yes" && property.PropertyDetail.GateSecurity != "No")
                return ValidationError("Invalid Gate security.");

            /*********** Locality Detail ***********/

            if (string.IsNullOrWhiteSpace(property.PropertyMaster.ContactPersonName))
                return ValidationError("Contact person name required.");
            else if(property.PropertyMaster.ContactPersonName.Length>50)
                return ValidationError("Contact person name can't be more than 50 characters.");

            if (string.IsNullOrWhiteSpace(property.PropertyMaster.ContactPersonMobile))
                return ValidationError("Contact person mobile no required.");
            else if (Validation.MobileNo(property.PropertyMaster.ContactPersonMobile))
                return ValidationError("Invalid contact person mobile no.");
            
            //if (string.IsNullOrWhiteSpace(property.PropertyMaster.City))
            //    return ValidationError("City required.");
           // if (!City.GetAll().ContainsKey(property.PropertyMaster.City))
             //   return ValidationError("Invalid city.");

            if (string.IsNullOrEmpty(property.PropertyMaster.Locality))
                return ValidationError("Locality required.");
            if(property.PropertyMaster.Locality.Length > 100)
                return ValidationError("Locality can't be greater than 100 characters.");

            if (string.IsNullOrEmpty(property.PropertyMaster.Latitude) || string.IsNullOrEmpty(property.PropertyMaster.Latitude))
                return ValidationError("Please select Locality from list.");

            if (!string.IsNullOrWhiteSpace(property.PropertyMaster.Street) && property.PropertyMaster.Street.Length > 100)
                return ValidationError("Property address can't be more than 100 characters.");

            /**************** Rental Detail **********/
            if (property.PropertyDetail.ExpectedRent == 0)
                return ValidationError("Expected Rent required.");
           

            if (!string.IsNullOrEmpty(property.PropertyDetail.AvailableFrom))
            {
                string availableFrom = property.PropertyDetail.AvailableFrom;
                DateTime outAvailableFrom;
                if (DateTime.TryParseExact(availableFrom, "dd-MM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out outAvailableFrom))
                {
                    property.PropertyDetail.AvailableFrom = DateTime.ParseExact(availableFrom, "dd-MM-yyyy", CultureInfo.InvariantCulture).ToString("yyyy-MM-dd");
                }
                else
                    return ValidationError("Invalid available from date format.");
            }
            
           if (!string.IsNullOrWhiteSpace(property.PropertyDetail.PreferredTenant) && !PreferredTenant.GetAll().ContainsKey(property.PropertyDetail.PreferredTenant))
                return ValidationError("Invalid preferred tenant type.");
 
            if (!string.IsNullOrWhiteSpace(property.PropertyDetail.Parking) && !ParkingType.GetAll().ContainsKey(property.PropertyDetail.Parking))
                return ValidationError("Invalid parking type.");

            if (string.IsNullOrWhiteSpace(property.PropertyDetail.Furnishing))
                return ValidationError("Furnishing type required.");
            if (!FurnishingType.GetAll().ContainsKey(property.PropertyDetail.Furnishing))
                return ValidationError("Invalid furnishing type.");
            else
            {
                if(property.PropertyDetail.Furnishing=="FF" || property.PropertyDetail.Furnishing == "SF")
                {
                    if (property.PropertyDetail.FurnishingDetails==null)
                        return ValidationError("Furnishing details required.");
                }
            }

            if (!string.IsNullOrWhiteSpace(property.PropertyDetail.Description) && property.PropertyDetail.Description.Length > 500)
                return ValidationError("Description can't be more than 500 characters.");

            property.PropertyDetail.ApartmentType =(!string.IsNullOrWhiteSpace(property.PropertyDetail.ApartmentType)?ApartmentType.GetAll().Where(x => x.Key == property.PropertyDetail.ApartmentType).Select(x => x.Value).FirstOrDefault():null);

            if (propertyType == "FLAT" || propertyType == "FLATMATE")

FH.Agent-Web/Views/Property/Edit.cshtml
@using FH.User.Entities;
@using FH.Web.Security;
@model Property
@{
    Layout = "~/Views/Shared/_LayoutWeb.cshtml";
    ViewBag.Title = "Update Property Detail";
    var jsVersion = System.Configuration.ConfigurationManager.AppSettings["JsVersioning"];
    string propertyType = "", propertyStatus = "";
    if(Model.PropertyFlatRoomFlatmate!=null && Model.PropertyFlatRoomFlatmate.PropertyMaster!=null)
    {
        propertyType = Model.PropertyFlatRoomFlatmate.PropertyMaster.PropertyType;
        propertyStatus =(!string.IsNullOrEmpty(Model.PropertyFlatRoomFlatmate.PropertyMaster.PropertyStatusByFH)? Model.PropertyFlatRoomFlatmate.PropertyMaster.PropertyStatusByFH.ToLower():"");
    }
    var isMobile = Request.Browser.IsMobileDevice;
}

@if (isMobile)
{ @Html.Partial("_Header_Mobile") }
else
{ @Html.Partial("_PartialHeader")}

<input type="hidden" id="propertyType" value="@propertyType" />
<input type="hidden" id="propertyId" value="@EncreptDecrpt.Encrypt(Model.PropertyFlatRoomFlatmate.PropertyMaster.PropertyId.ToString())" />
<div class="clearfix"></div><br />
<div class="postPropertySection">
    <div class="container">
        <div class="row" id="dv_container_row">            
            <div class="col-md-8">
                <div class="postPropertyBox" style="border:1px solid #eee">
                    <div class="tab-content">
                        <div id="property_detail_info">
                            @Html.Partial("_EditPropertyDetail",Model.PropertyFlatRoomFlatmate.PropertyDetail, new ViewDataDictionary { { "propertyType",propertyType}, {"propertyStatus",propertyStatus } })
                        </div>
                        <div id="locality_info" class="d_none">
                            @Html.Partial("_EditLocalityDetail",Model.PropertyFlatRoomFlatmate.PropertyMaster, new ViewDataDictionary {{ "propertyStatus", propertyStatus }})
                        </div>
                        <div id="rental_info" class="d_none">
                            @Html.Partial("_EditRentalDetail",Model.PropertyFlatRoomFlatmate.PropertyDetail,new ViewDataDictionary { { "furnishMaster",Model.FurnishMaster}, { "propertyStatus", propertyStatus }})
                        </div>
                        <div id="gallery_info" class="d_none">
                            @Html.Partial("_EditGallery",Model.PropertyFlatRoomFlatmate.GalleryDetails, new ViewDataDictionary { { "propertyStatus", propertyStatus } })
                        </div>
                        <div id="amenity_info" class="d_none">                            
                            @Html.Partial("_EditAmenity",Model.PropertyFlatRoomFlatmate.AmenityDetails,new ViewDataDictionary { { "amenityMaster", Model.AmenityMaster }, { "propertyStatus", propertyStatus } })
                        </div>
                    </div>
                </div>
            </div>
            @if (!Request.Browser.IsMobileDevice)
            {
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="postYourPropertyContent">
                                <h4>Why Post through us?</h4>
                                <ul class="why-post-content">
                                    <li>Free Listing</li>
                                    <li>Higher Profitability</li>
                                    <li>Greater Transparency</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

 @section Script{
    <script type="text/javascript" src="@Url.Content("/Content/js/property.js?v="+jsVersion)"></script>
    <link href="~/Content/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.js"></script>
    <script src="~/Content/js/bootstrap-datetimepicker.min.js"></script>
<script>
    $(function () {
        $('#avaliable_from').datetimepicker({
            format: 'dd-mm-yyyy',
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            startDate: '-0d'
        });
        $('.prev').html('<i class="fas fa-chevron-left"></i>');
        $('.next').html('<i class="fas fa-chevron-right"></i>');
    });
</script>
}

FH.Agent-Web/Views/Property/EditPG.cshtml
@using FH.User.Entities;
@using FH.Web.Security;
@model Property
@{
    Layout = "~/Views/Shared/_LayoutWeb.cshtml";
    ViewBag.Title = "Update PG Detail";
    var jsVersion = System.Configuration.ConfigurationManager.AppSettings["JsVersioning"];
    string propertyStatus = (!string.IsNullOrEmpty(Model.PropertyPG.PropertyMaster.PropertyStatusByFH) ? Model.PropertyPG.PropertyMaster.PropertyStatusByFH.ToLower() : "");
    string dnone = "d_none";
    var isMobile = Request.Browser.IsMobileDevice;
}
@if (isMobile)
{@Html.Partial("_Header_Mobile") }
else
{ @Html.Partial("_PartialHeader")}
<input type="hidden" id="propertyType" value="PG" />
<input type="hidden" id="propertyId" value="@EncreptDecrpt.Encrypt(Model.PropertyPG.PropertyMaster.PropertyId.ToString())" />
<div class="clearfix"></div>
<br />
<div class="postPropertySection">
    <div class="container-fluid">
        <div class="row" id="dv_container_row">
            <div class="col-md-10">
                <div class="postPropertyBox" style="border:1px solid #eee">
                    <div class="tab-content">
                        <div id="pg_room_info" class="@if(Model.lavel != "pg_room_info" && Model.lavel != "") { @dnone }">
                            @Html.Partial("_EditPGRoomDetail", Model.PropertyPG.RoomRentalDetail, new ViewDataDictionary { { "roomAmenities", Model.PropertyPG.RoomAmenities }, { "roomAmenityMaster", Model.AmenityMaster.Where(x => x.AmenityType == "PGRoom") }, { "propertyStatus", propertyStatus } })
                        </div>
                        <div id="locality_info" class="@if(Model.lavel != "locality_info") { @dnone }">
                            @Html.Partial("_EditLocalityDetail", Model.PropertyPG.PropertyMaster, new ViewDataDictionary { { "propertyStatus", propertyStatus } })
                        </div>
                        <div id="pg_info" class="@if(Model.lavel != "pg_info") { @dnone }">
                            @Html.Partial("_EditPGDetail", Model.PropertyPG.PgDetail, new ViewDataDictionary { { "pgRules", Model.PropertyPG.pgRules }, { "propertyStatus", propertyStatus } })
                        </div>
                        <div id="gallery_info" class="@if(Model.lavel != "gallery_info") { @dnone }">
                            @Html.Partial("_EditGallery", Model.PropertyPG.GalleryDetails, new ViewDataDictionary { { "propertyStatus", propertyStatus } })
                        </div>
                        <div id="amenity_info" class="@if(Model.lavel != "amenity_info") { @dnone }">
                            @Html.Partial("_EditAmenity", Model.PropertyPG.AmenityDetails, new ViewDataDictionary { { "amenityMaster", Model.AmenityMaster.Where(x => x.AmenityType == "PG") }, { "propertyStatus", propertyStatus } })
                        </div>
                        <div id="room_info" class="@if(Model.lavel != "room_info") { @dnone }">
                            @Html.Partial("_EditRoom", Model.PropertyPG.PGRoomData, new ViewDataDictionary { { "amenityMaster", Model.AmenityMaster.Where(x => x.AmenityType == "PG") }, { "propertyStatus", propertyStatus }, { "UAccount", Model.PropertyPG.UAccount } })
                        </div>
                    </div>
                </div>
            </div>
            @if (!Request.Browser.IsMobileDevice)
            {
                <div class="col-md-2">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="postYourPropertyContent">
                                <h4>Why Post through us?</h4>
                                <ul class="why-post-content">
                                    <li>Free Listing</li>
                                    <li>Higher Profitability</li>
                                    <li>Greater Transparency</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div id="snackbar"></div>
@section Script{
    <script type="text/javascript" src="@Url.Content("/Content/js/property-pg.js?v="+jsVersion)"></script>
    <link href="~/Content/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.js"></script>
    <script src="~/Content/js/bootstrap-datetimepicker.min.js"></script>
    <script>
        $(function () {
            $('#avaliable_from').datetimepicker({
                format: 'dd-mm-yyyy',
                todayBtn: 1,
                autoclose: 1,
                todayHighlight: 1,
                startView: 2,
                minView: 2,
                startDate: '-0d'
            });
            $('.prev').html('<i class="fas fa-chevron-left"></i>');
            $('.next').html('<i class="fas fa-chevron-right"></i>');
        });
    </script>
}

FH.Agent-Web/Views/Property/PostPG.cshtml
@using FH.Web.Security;
@{
    Layout = "~/Views/Shared/_LayoutWeb.cshtml";
    ViewBag.Title = "Post Your PG";
    var jsVersion = System.Configuration.ConfigurationManager.AppSettings["JsVersioning"];
    var isMobile = Request.Browser.IsMobileDevice;
}
@if (isMobile)
{@Html.Partial("_Header_Mobile")
if (CurrentUser.User != null && !string.IsNullOrWhiteSpace(CurrentUser.User.Roles[0]) && (CurrentUser.User.Roles[0].ToUpper() == "AGENT" || CurrentUser.User.Roles[0].ToUpper() == "OWNER"))
{
    @Html.Partial("_Menu_Mobile")
}
}
else
{ @Html.Partial("_PartialHeader")}

<div class="clearfix"></div>
<br />
<div class="postPropertySection">
    <div class="container">
        <div class="row" id="dv_container_row">
            <div class="col-md-8">
                <div class="postPropertyBox" style="border:1px solid #eee">
                    <div class="tab-content">
                        <div id="pg_room_info">
                            @Html.Partial("_AddPGRoomDetail", new ViewDataDictionary { { "roomAmenity", ViewBag.roomAmenity } })
                        </div>
                        <div id="locality_info" class="d_none">
                            @Html.Partial("_AddLocalityDetail")
                        </div>
                        <div id="pg_info" class="d_none">
                            @Html.Partial("_AddPGDetail")
                        </div>
                        <div id="gallery_info" class="d_none">
                            @Html.Partial("_AddGallery")
                        </div>
                        <div id="amenity_info" class="d_none">
                            @Html.Partial("_AddAmenity", new ViewDataDictionary { { "amenityMaster", ViewBag.pgAmenity } })
                        </div>
                    </div>
                </div>
            </div>
            @if (!Request.Browser.IsMobileDevice)
            {
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="postYourPropertyContent">
                                <h4>Why Post through us?</h4>
                                <ul class="why-post-content">
                                    <li>Free Listing</li>
                                    <li>Higher Profitability</li>
                                    <li>Greater Transparency</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section Script{
    <script type="text/javascript" src="@Url.Content("/Content/js/property-pg.js?v="+jsVersion)"></script>
    <link href="~/Content/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.js"></script>
    <script src="~/Content/js/bootstrap-datetimepicker.min.js"></script>
    <script>
        $(function () {
            $('#avaliable_from').datetimepicker({
                format: 'dd-mm-yyyy',
                todayBtn: 1,
                autoclose: 1,
                todayHighlight: 1,
                startView: 2,
                minView: 2,
                startDate: '-0d'
            });
            $('.prev').html('<i class="fas fa-chevron-left"></i>');
            $('.next').html('<i class="fas fa-chevron-right"></i>');
        });
    </script>
}

FH.Agent-Web/Views/Property/_AddAmenity.cshtml
@using FH.User.Entities;
@{ 
    var amenityMaster = (IEnumerable<AmenityMaster>)ViewData["amenityMaster"];
}
<div class="col-md-12"><h4 class="text-primary">Provide additional details about your property to get maximum visibilty.</h4></div>
<div class="clearfix"></div><hr>
<h4 class="ml-3">Select the amenities available</h4>
@if (amenityMaster != null)
{
    <div class="row m-0">
        @foreach (var item in amenityMaster)
        {
        <div class="col-md-4 pr-0">
            <div>
                <div class="dv-list-item amenity" data-key="@item.AmenityId">@item.AmenityName</div>
            </div>            
        </div>
        }
    </div>
}
<div class="clearfix"></div><hr>
<div class="text-center">
    <button class="btn btn-secondary" id="btn_amenity_back">Back</button>
    <button id="btn_amenity" class="btn btn-primary">Submit</button>
</div>

FH.Agent-Web/Views/Property/_AddGallery.cshtml
<div class="col-md-12"><h4 class="text-primary">Upload photo gallery</h4></div>
<div class="clearfix"></div><hr>
<div class="col-md-12">    
        <form id="frmFileUpload" action="#" method="POST" enctype="multipart/form-data" class="">
            <input id="fileUpload" type="file" accept="image/jpeg,image/png,image/jpg" class="d_none" multiple>
            <div class="col-md-12 first-box">
                <div class="upload-images-box" onclick="fileUploader();">
                    <img src="~/Content/images/add-more-image.png">
                    <div class="clearfix"></div>
                    <span class="btn btn-primary mt-4 mb-4">
                        <span>Upload Photos</span>
                    </span>
                    <ul class="image-instructions">
                        <li>Max limit 5 MB per image</li>
                        <li>Upload at least 5 photos to increase property quality</li>
                    </ul>
                </div>
            </div>
            <ul class="post-property-iamges">                                
                <li class="d_none">
                    <div class="add-more-photos fileinput-button-more" onclick="fileUploader();">
                        <h2>+</h2> 
                        <p>Add More Photos</p>
                    </div>
                </li>
            </ul>
            <div class="clearfix"></div><br>            
            <ul class="image-instructions ins2 d_none">
                <li>Max limit 5 MB per image</li>
                <li>Upload at least 5 photos to increase property quality</li>
            </ul>            
        </form>
        <br>    
</div>
<div class="clearfix"></div><hr>
<div class="text-center">
    <button class="btn btn-secondary" id="btn_gallery_back">Back</button>
    <button id="btnGallery" class="btn btn-primary">Submit</button>
</div>

<script>   

    $('#fileUpload').on('change', uploadFiles);

    function uploadFiles(event)
    {
        if (window.FormData !== undefined) {
            var fileUpload = $("#fileUpload").get(0);
            var files = fileUpload.files;
            $('.first-box').hide();
            $('.add-more-photos').parent().removeClass('d_none');
            $('.ins2').removeClass('d_none');
            for (var i = 0; i < files.length; i++) {
                var l = $('.post-property-iamges li').length - 1;
                $('.post-property-iamges').append('<li class="li'+l+'"><div class="upload-loader"><div class="img-upload-loader"></div></div></li>');                
                var formData = new FormData(document.getElementById("frmFileUpload"));
                formData.append(files[i].name, files[i]);
                formData.append("Id",l);
                $.ajax({
                    url: "@Url.Action("UploadGallery", "Property")",
                    type: "POST",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,                   
                    success: function (data, status) {
                        debugger;
                        if (data.Success == true) {
                            var file = { FilePath: data.Url,FileName:data.File }
                            propertyPost.GalleryDetails.push(file);
                            $('.post-property-iamges .li' + data.Id).css('background', 'url("' + data.Url + '")');                            
                            $('.post-property-iamges .li' + data.Id + ' .upload-loader').remove();
                            $('.li' + data.Id).append('<span class="remove-picture" data-file="'+data.File+'" data-url="'+data.Url+'"><i class="fas fa-trash-alt"></i></span>');
                        }
                        else
                            $('.post-property-iamges .li' + data.Id).remove();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        showError("Something went wrong.Please try again.");
                    }                    
                });
            }
        }
        else {
            showError("This browser is not supported,Please try another.");
        }    
    }
      function fileUploader() {
            $('#fileUpload').click();
        }

</script>

FH.Agent-Web/Views/Property/_AddRentalDetail.cshtml
<div class="col-md-12"><h4 class="text-primary">Provide rental details about your property</h4></div>
<div class="clearfix"></div><hr>

<div class="col-md-12">
    <div class="form-group">
        <div class="row m-0">
            <div class="col-md-4 pl-0">
                <label>Expected Rent<span class="mondatoryStar">*</span></label>
                <input type="number" id="rent" value="" class="form-control" placeholder="Monthly Rent" maxlength="6" autocomplete="off">
                <label><input type="checkbox" name="rent_negotiable" value="" /> Negotiable</label>
            </div>
            <div class="col-md-4 pl-0">
                <label>Expected Deposit<span class="mondatoryStar">*</span></label>
                <input type="number" id="deposit" value="" class="form-control" placeholder="Deposit Amount" maxlength="6" autocomplete="off">
            </div>
            <div class="col-md-4 pl-0">
                <label>Available From</label>
                <input type="text" id="avaliable_from" value="" class="form-control" placeholder="dd-mm-yyyy" autocomplete="off">
            </div>
        </div>
    </div>   
    <div class="form-group">        
            <label>Preferred Tenants<span class="mondatoryStar">*</span></label>
            <div>
                @foreach (var entry in PreferredTenant.GetAll())
            {
                    <div class="dv-list-item preferred_tenant" data-key="@entry.Key">@entry.Value</div>
            }
        
        </div>       
    </div>
    <div class="form-group">
        <label>Parking</label>
        <div>
            @foreach (var entry in ParkingType.GetAll())
            {
                <div class="dv-list-item parking" data-key="@entry.Key">@entry.Value</div>
            }
        </div>                        
    </div>
    <div class="form-group">
        <label>Furnishing<span class="mondatoryStar">*</span></label>
        <div>
            @foreach (var entry in FurnishingType.GetAll())
            {
                <div class="dv-list-item furnish" data-key="@entry.Key">@entry.Value</div>
            }
        </div>                                
    </div>    
        @Html.Partial("_AddFurnishDetail", ViewData["furnishMaster"])    
    <div class="form-group">
        <label>Description</label>
        <textarea id="description" class="form-control" rows="4" placeholder="Write a few lines about your property. Let the tenant know the amenities available, type of neighbourhood, proximity to bus and train stations etc."></textarea>        
    </div>
</div>
<div class="clearfix"></div><hr>
<div class="text-center">
    <button class="btn btn-secondary" id="btn_back_rental">Back</button>
    <button id="btn_rental" class="btn btn-primary">Submit</button>
</div>